### ISSUE TITLE
项目无法启动

### ISSUE THREAD

**Issue by piu1283** [Mensu/YueLiBack#4]
你好，我 clone 了项目之后，使用 npm install 然后 npm run dev , 之后提示这个：

![image](https://user-images.githubusercontent.com/35473890/57118338-26cc7900-6d95-11e9-81a8-346937a63e10.png)

同样我使用 npm run start， 之后状态也是 errored，

![image](https://user-images.githubusercontent.com/35473890/57118378-86c31f80-6d95-11e9-9b6c-a6117fc22bf0.png)

但是我按照给出的地址查看日志并没有日志记录。

**Comment by Mensu** [comment]
@piu1283 项目开发时使用的是 node 9。使用最新版本的 node 的话，需要更新 @std/esm。

```
npm i esm
```

然后修改 `entry.js` 为 `require('esm')(module)('./src')`（原来是 `require('@std/esm')`

**Comment by piu1283** [comment]
可以了，非常感谢！
